In [10]:
from transformers import pipeline

# Load emotion detection pipeline
emotion_detector = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

# Predict emotions
text = " can't believe this keeps happening"
result = emotion_detector(text)
print(result)


Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


[{'label': 'surprise', 'score': 0.9422865509986877}]


In [2]:
pip install keras==2.11 tensorflow==2.11


ERROR: Could not find a version that satisfies the requirement tensorflow==2.11 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for tensorflow==2.11
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tf-keras

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 3.5 MB/s eta 0:00:00ta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.6/239.6 MB 10.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 10.4 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.17.0
    Uninstalling tensorboard-2.17.0:
      Successfully uninstalled tensorboard-2.17.0
  Attempting uninstall: keras
    Found existing installation: keras 3.4.1
    Uninstalling keras-3.4.1:
      Successfully uninstalled keras-3.4.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.17.0
    Uninstalling tensorflow-2.17.0:
      Successfully uninstalled tensorflow-2.17.0

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated 

In [2]:
from transformers import pipeline

# Load the pre-trained model
emotion_detector = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

# Define a mapping dictionary
custom_label_mapping = {
    "joy": 1,        # Map 'joy' to 1
    "neutral": 0,    # Map 'neutral' to 0
    "sadness": 2,    # Map 'sadness' to 2
}

# Define a function to map model predictions to custom labels
def map_emotions_to_custom_labels(text):
    result = emotion_detector(text)
    original_label = result[0]["label"]  # Get the predicted label
    custom_label = custom_label_mapping.get(original_label, -1)  # Map to custom label (-1 if not mapped)
    return {"text": text, "original_label": original_label, "custom_label": custom_label}

# Test the function
test_texts = [
    "I am extremely happy today!",    # Should map to 1
    "It's just an ordinary day.",     # Should map to 0
    "I feel really down and sad.",    # Should map to 2
]

for text in test_texts:
    output = map_emotions_to_custom_labels(text)
    print(output)


Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


{'text': 'I am extremely happy today!', 'original_label': 'joy', 'custom_label': 1}
{'text': "It's just an ordinary day.", 'original_label': 'neutral', 'custom_label': 0}
{'text': 'I feel really down and sad.', 'original_label': 'sadness', 'custom_label': 2}


In [7]:
from transformers import pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd
import numpy as np

# Load the dataset
file_path = 'tweet_emotions.csv'  # Adjust the path if needed
data = pd.read_csv(file_path)

# Load the emotion detection pipeline
emotion_detector = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

# Subset the data for faster testing
sample_data = data.sample(1000, random_state=42)
texts = sample_data['content'].tolist()
true_labels = sample_data['sentiment'].tolist()

# Get predictions
predictions = [emotion_detector(text)[0]['label'] for text in texts]

# Calculate accuracy
accuracy = accuracy_score(true_labels, predictions)

# Generate confusion matrix and classification report
conf_matrix = confusion_matrix(true_labels, predictions, labels=np.unique(true_labels))
class_report = classification_report(true_labels, predictions)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)


Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


Accuracy: 0.18

Confusion Matrix:
 [[ 0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  5  0  5  4  0]
 [ 0  0  0  0  0  0  0  5  0  4  8  0]
 [ 0  0  0  0  0  0  0  1  0  4 15  0]
 [ 0  0  0  0  0  0  0 13  0 11 28  0]
 [ 0  0  0  0  0  0  0  0  0 10  2  0]
 [ 0  0  0  0  0  0  0 10  0 12 14  0]
 [ 0  0  0  0  0  0  0 59  0 44 60  0]
 [ 0  0  0  0  0  0  0 10  0  9  9  0]
 [ 0  0  0  0  0  0  0  9  0 87 21  0]
 [ 0  0  0  0  0  0  0  6  0  4 34  0]
 [ 0  0  0  0  0  0  0 26  0 99 44  0]]

Classification Report:
               precision    recall  f1-score   support

       anger       0.00      0.00      0.00         0
     boredom       0.00      0.00      0.00         4
     disgust       0.00      0.00      0.00         0
       empty       0.00      0.00      0.00        18
  enthusiasm       0.00      0.00      0.00        23
        fear       0.00      0.00      0.00         0
         fun       0.00      0.00      0.00        34
   happiness       0.00      0.00     

/Users/bhoomi/Desktop/veenus/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/bhoomi/Desktop/veenus/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/bhoomi/Desktop/veenus/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", l